### ISSUE TITLE
海康摄像头RTSP拉流，视频录制异常

### ISSUE THREAD

**Issue by Lijunmin76** [Monibuca/plugin-record#8]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x155b620]

goroutine 35 [running]:
m7s.live/engine/v4/track.(*Audio).ReadRing(0x16b2a60?)
	<autogenerated>:1
m7s.live/engine/v4.(*PlayContext[...]).init(...)
	D:/GoPrj/golangDeps/pkg/mod/m7s.live/engine/v4@v4.3.0/subscriber.go:85
m7s.live/engine/v4.(*Subscriber).AddTrack(0xc00017a300, {0x183eb78?, 0x0?})
	D:/GoPrj/golangDeps/pkg/mod/m7s.live/engine/v4@v4.3.0/subscriber.go:133 +0x1ad
m7s.live/engine/v4.(*Subscriber).OnEvent(0xc00017a300, {0x175c820?, 0x0})
	D:/GoPrj/golangDeps/pkg/mod/m7s.live/engine/v4@v4.3.0/subscriber.go:116 +0x132
m7s.live/plugin/record/v4.(*Recorder).OnEvent(0xc00017a300?, {0x175c820?, 0x0?})
	D:/GoPrj/golangDeps/pkg/mod/m7s.live/plugin/record/v4@v4.0.0-20220620045616-933fb3cceda5/subscriber.go:42 +0x105
m7s.live/plugin/record/v4.(*MP4Recorder).OnEvent(0xc00017a300, {0x175c820?, 0x0?})
	D:/GoPrj/golangDeps/pkg/mod/m7s.live/plugin/record/v4@v4.0.0-20220620045616-933fb3cceda5/mp4.go:86 +0x58
m7s.live/plugin/record/v4.(*MP4Recorder).OnEvent(0xc00017a300, {0x16d1760?, 0xc000324970?})
	D:/GoPrj/golangDeps/pkg/mod/m7s.live/plugin/record/v4@v4.0.0-20220620045616-933fb3cceda5/mp4.go:154 +0x825
m7s.live/engine/v4.(*Subscriber).PlayBlock.func3(0x1841d00?)
	D:/GoPrj/golangDeps/pkg/mod/m7s.live/engine/v4@v4.3.0/subscriber.go:184 +0x2f
m7s.live/engine/v4.(*Subscriber).PlayBlock(0xc00017a300, 0x0)
	D:/GoPrj/golangDeps/pkg/mod/m7s.live/engine/v4@v4.3.0/subscriber.go:280 +0xd95
m7s.live/engine/v4.(*Subscriber).PlayRaw(...)
	D:/GoPrj/golangDeps/pkg/mod/m7s.live/engine/v4@v4.3.0/subscriber.go:147
m7s.live/plugin/record/v4.(*Recorder).Start(0xc00017a300)
	D:/GoPrj/golangDeps/pkg/mod/m7s.live/plugin/record/v4@v4.0.0-20220620045616-933fb3cceda5/subscriber.go:19 +0x25
created by m7s.live/plugin/record/v4.(*MP4Recorder).OnEvent
	D:/GoPrj/golangDeps/pkg/mod/m7s.live/plugin/record/v4@v4.0.0-20220620045616-933fb3cceda5/mp4.go:138 +0x9c5

**Comment by langhuihui** [comment]
有拉流的日志吗
